name: CI

on:
  push:
    branches-ignore: ['gh-pages']
    tags: ['*']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-lint')"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Linter
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip-build')"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build
  
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build TGVCBot
        run: pnpm run build --filter=tgvcbot
      
      - name: Pack Build
        run: |
          cd apps/tgvcbot
          mv $(pnpm pack) ../../archive.tgz
      - uses: softprops/action-gh-release@v1
        with:
          files: archive.tgz
          generate_release_notes: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
